#
# Add YAML properties here to override PREPROD environment settings
# Properties from base/configuration.yaml are applied first, then settings here override those.
#
# Enable this configuration by passing -Dprofile=PREPROD during application startup
#
